Convert the output of unpushed branch check to lower case
In commit 3a429d0 of git, the casing of certain error messages was
changed, convert the message to lower case before comparison.

    ERROR: Command failed: git rev-parse --abbrev-ref benbrown/foo@{upstream}
    fatal: no upstream configured for branch 'benbrown/foo'

Change-Id: I5e0659b69f3be84820592b7fe26e50203272da22