morphlib/git: Ignore not valid submodules
Some repositories may have submodules listed in .gitmodules that
are not pointing to a commit object in the tree. This was causing
the following error:

    ERROR: /srv/distbuild/gits/git___git_foo_bar_git:c36652c7dd9f1687c87ce04ad3d4af2beb52dc25:.gitmodules: No commit object found for submodule "codegen"

Instead of raising that error, capture it and ignore the submodule.

Change-Id: Iba0428feea7605f797dc78e3e250f3d66c003670