More robust creation of cache dirs
When starting various distbuilds at the same time we were
having randomly errors like:

    2016-01-06 12:14:03 Starting distributed build
    2016-01-06 12:14:03 Connecting to mason-x86-64:7878
    2016-01-06 12:14:03 Requesting build of git://192.168.222.58/baserock/baserock/definitions 28b92192c00a36395acd6a960959d3b4468f9894 systems/openstack-system-x86_64.morph
    ERROR: /srv/distbuild/artifacts: File exists
    ERROR: /srv/distbuild/artifacts: File exists
    ERROR: /srv/distbuild/artifacts: File exists
    ERROR: /srv/distbuild/artifacts: File exists

This has been happening in Mason since we remove every folder
used by Morph after Mason finishes.

Change-Id: I175de7282302d9c1e2fb1b0872f7eb72c742f28e