Make source resolver pass filename
Passing the filename when loading a morphology
lets us give a more useful error message:

e.g. ERROR: Missing field name from morphology strata/build-essential.morph

instead of

ERROR: Missing field name from morphology string

Change-Id: I2e5b33e8154567469aa56adbf942fb7b6e9dd1ac