morphlib/git: Fix update_submodules
It seems to be broken since d58d8e8f7a4ec03ff14021a4515c8283dad52573
and it's making `morph get-repo` fail with:

    /src/definitions # morph get-repo ansible
    2016-04-06 11:36:31 Loading in all morphologies
    2016-04-06 11:36:32 Checking out ref 0a7124541247cc613352054f4bc0c3e116e0b657 of ansible in ansible stratum
    Traceback (most recent call last):
      File "cliapp/app.py", line 190, in _run
        self.process_args(args)
      File "/src/morph/morphlib/app.py", line 299, in process_args
        cliapp.Application.process_args(self, args)
      File "cliapp/app.py", line 539, in process_args
        method(args[1:])
      File "/src/morph/morphlib/plugins/get_repo_plugin.py", line 142, in get_repo
        chunk_dirname = checkout_chunk(morph, chunk)
      File "/src/morph/morphlib/plugins/get_repo_plugin.py", line 110, in checkout_chunk
        ref or chunk_spec['ref'])
      File "/src/morph/morphlib/plugins/get_repo_plugin.py", line 60, in _clone_repo
        gd.update_submodules(self.app)
      File "/src/morph/morphlib/gitdir.py", line 527, in update_submodules
        morphlib.git.update_submodules(app, self.dirname)
      File "/src/morph/morphlib/git.py", line 150, in update_submodules
        submodules.load()
      File "/src/morph/morphlib/git.py", line 69, in load
        content = self._read_gitmodules_file()
      File "/src/morph/morphlib/git.py", line 82, in _read_gitmodules_file
        ignore_fail=True)
      File "/src/morph/morphlib/git.py", line 306, in gitcmd
        return runcmd(cmdline, **kwargs)
    TypeError: 'str' object is not callable

Change-Id: I8d08eb71a2b0a773bc4322ed46222bea0adbbee1