Error when different names in system/strata
Now is an error when the name of a stratum in a system is different from
the name of the stratum in the stratum file. Example of the error message:

    ERROR: Name 'build-essential-foo' doesn't match 'build-essential' in morphology: strata/build-essential.morph

We are forcing the error here instead of a warning because this problem
makes Morph create broken systems.

https://storyboard.baserock.org/#!/story/15

Change-Id: Ifbe8d98e64a768e4e238d2213ffaf575789dd9e2