More robust creation of tempdirs
This commit addresses the same issue that we tried to solve in
fa431c3ce38204f5237337fd2045ad6269413258 but this time with temp dirs:

    + echo INFO: Mason building: master at
    fe64c00f17a4922c7499f9bc48f672cca293fc65
    INFO: Mason building: master at fe64c00f17a4922c7499f9bc48f672cca293fc65
    + scripts/release-build --no-default-configs --trove-host 192.168.222.58
    --artifact-cache-server http://192.168.222.14:8080/ --controllers
    x86_64:mason-x86-64 clusters/ci.morph
    ERROR: /srv/distbuild/tmp/chunks: File exists
    ERROR: /srv/distbuild/tmp/chunks: File exists

This has been happening in Mason since we remove every folder
used by Morph after Mason finishes.

Change-Id: I5a5bfd3c01b6fd0da4b913c5bb8eac77a3233d1e